services:

  db-auth:
    image: postgres:15
    container_name: db-auth
    environment:
      POSTGRES_DB: bd_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5436:5432"
    volumes:
      - db-auth-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  authentication:
    build: ../authentication
    container_name: authentication
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-auth:5432/bd_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db-auth:
        condition: service_healthy
    networks:
      - cordillera-net

  db-ventas:
    image: postgres:15
    container_name: db-ventas
    environment:
      POSTGRES_DB: bd_ventas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - db-ventas-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ventas:
    build: ../ventas
    container_name: ventas
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-ventas:5432/bd_ventas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db-ventas:
        condition: service_healthy
    networks:
      - cordillera-net

  db-inventario:
    image: postgres:15
    container_name: db-inventario
    environment:
      POSTGRES_DB: bd_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - db-inventario-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s 
      retries: 5

  inventario:
    build: ../inventario
    container_name: inventario
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-inventario:5432/bd_inventario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db-inventario:
        condition: service_healthy
    networks:
      - cordillera-net

  db-finanzas:
    image: postgres:15
    container_name: db-finanzas
    environment:
      POSTGRES_DB: bd_finanzas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5435:5432"
    volumes:
      - db-finanzas-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  finanzas:
    build: ../finanzas
    container_name: finanzas
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-finanzas:5432/bd_finanzas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db-finanzas:
        condition: service_healthy
    networks:
      - cordillera-net

  db-clientes:
    image: postgres:15
    container_name: db-clientes
    environment:
      POSTGRES_DB: bd_clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5437:5432"
    volumes:
      - db-clientes-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  clientes:
    build: ../clientes
    container_name: clientes
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-clientes:5432/bd_clientes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db-clientes:
        condition: service_healthy
    networks:
      - cordillera-net

  db-alertas:
    image: postgres:15
    container_name: db-alertas
    environment:
      POSTGRES_DB: bd_alertas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5438:5432"
    volumes:
      - db-alertas-data:/var/lib/postgresql/data
    networks:
      - cordillera-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-alertas:
    build: ../alertas
    container_name: ms-alertas
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-alertas:5432/bd_alertas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      INVENTARIO_URL: http://inventario:8083/inventario
      VENTAS_URL: http://ventas:8082/ventas
      FINANZAS_URL: http://finanzas:8084/finanzas
      ALERTAS_DETECCION_DELAY_MS: 15000
    depends_on:
      db-alertas:
        condition: service_healthy
      inventario:
        condition: service_started
      ventas:
        condition: service_started
      finanzas:
        condition: service_started
    networks:
      - cordillera-net

  ms-kpis:
    build: ../kpis
    container_name: ms-kpis
    ports:
      - "8086:8086"
    environment:
      VENTAS_URL: http://ventas:8082/ventas
      INVENTARIO_URL: http://inventario:8083/inventario
      FINANZAS_URL: http://finanzas:8084/finanzas
      CLIENTES_URL: http://clientes:8085/clientes
    depends_on:
      - authentication
      - ventas
      - inventario
      - finanzas
      - clientes
    networks:
      - cordillera-net

  ms-reportes:
    build: ../reportes
    container_name: ms-reportes
    ports:
      - "8088:8088"
    environment:
      VENTAS_URL: http://ventas:8082/ventas
      INVENTARIO_URL: http://inventario:8083/inventario
      FINANZAS_URL: http://finanzas:8084/finanzas
    depends_on:
      - ventas
      - inventario
      - finanzas
    networks:
      - cordillera-net

  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      KPIS_URL: http://ms-kpis:8086
    depends_on:
      - authentication
      - ventas
      - inventario
      - finanzas
      - clientes
      - ms-alertas
      - ms-kpis
      - ms-reportes
    networks:
      - cordillera-net

volumes:
  db-auth-data:
  db-ventas-data:
  db-inventario-data:
  db-finanzas-data:
  db-clientes-data:
  db-alertas-data:

networks:
  cordillera-net:
    driver: bridge
