server.port=8080
spring.application.name=api-gateway

# Autenticación
spring.cloud.gateway.server.webmvc.routes[0].id=authentication
spring.cloud.gateway.server.webmvc.routes[0].uri=http://authentication:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

# Ventas
spring.cloud.gateway.server.webmvc.routes[1].id=ventas
spring.cloud.gateway.server.webmvc.routes[1].uri=http://ventas:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/ventas/**

# Inventario
spring.cloud.gateway.server.webmvc.routes[2].id=inventario
spring.cloud.gateway.server.webmvc.routes[2].uri=http://inventario:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/inventario/**

# Finanzas
spring.cloud.gateway.server.webmvc.routes[3].id=finanzas
spring.cloud.gateway.server.webmvc.routes[3].uri=http://finanzas:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/finanzas/**

# Clientes
spring.cloud.gateway.server.webmvc.routes[4].id=clientes
spring.cloud.gateway.server.webmvc.routes[4].uri=http://ms_clientes:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/clientes/**

# KPIs
spring.cloud.gateway.server.webmvc.routes[5].id=kpis
spring.cloud.gateway.server.webmvc.routes[5].uri=http://ms_kpis:8086
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/kpis/**

# Alertas
spring.cloud.gateway.server.webmvc.routes[6].id=alertas
spring.cloud.gateway.server.webmvc.routes[6].uri=http://ms_alertas:8087
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/alertas/**

# Reportes
spring.cloud.gateway.server.webmvc.routes[7].id=reportes
spring.cloud.gateway.server.webmvc.routes[7].uri=http://ms_reportes:8088
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/reportes/**

# JWT
jwt.secret=clave-secreta-grupo-cordillera-2025-muy-larga
