spring.application.name=ms-kpis
server.port=${PORT:8086}

# URLs configurables para local y Docker
app.services.ventas-url=${VENTAS_URL:http://localhost:8082/ventas}
app.services.inventario-url=${INVENTARIO_URL:http://localhost:8083/inventario}
app.services.finanzas-url=${FINANZAS_URL:http://localhost:8084/finanzas}
app.services.clientes-url=${CLIENTES_URL:http://localhost:8085/clientes}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
