spring.application.name=alertas
server.port=${PORT:8087}

app.services.inventario-url=${INVENTARIO_URL:http://localhost:8083/inventario}
app.services.ventas-url=${VENTAS_URL:http://localhost:8082/ventas}
app.services.finanzas-url=${FINANZAS_URL:http://localhost:8084/finanzas}

alertas.deteccion.delay-ms=${ALERTAS_DETECCION_DELAY_MS:15000}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bd_alertas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Reducir tamaño del pool de conexiones para Render free plan
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.baseline-on-migrate=true
