spring.application.name=ventas
server.port=8082

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bd_ventas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Resilience4j
resilience4j.circuitbreaker.instances.ms-ventas.sliding-window-size=10
resilience4j.circuitbreaker.instances.ms-ventas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-ventas.wait-duration-in-open-state=5s