spring.application.name=ventas
server.port=${PORT:8082}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bd_ventas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# Reducir tamaño del pool de conexiones para Render free plan
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Resilience4j
resilience4j.circuitbreaker.instances.finanzas.sliding-window-size=10
resilience4j.circuitbreaker.instances.finanzas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.finanzas.wait-duration-in-open-state=5s

# Reintento de sincronizacion con finanzas
finanzas.reintento.delay-ms=60000

# URLs de microservicios para Feign Clients
app.services.inventario-url=${INVENTARIO_URL:http://localhost:8083/inventario}
app.services.finanzas-url=${FINANZAS_URL:http://localhost:8084/finanzas}
app.services.clientes-url=${CLIENTES_URL:http://localhost:8085/clientes}
