spring.application.name=reportes

server.port=8088

app.services.ventas-url=${VENTAS_URL:http://localhost:8082/ventas}
app.services.inventario-url=${INVENTARIO_URL:http://localhost:8083/inventario}
app.services.finanzas-url=${FINANZAS_URL:http://localhost:8084/finanzas}

spring.mvc.problemdetails.enabled=true
